FROM python:3.12.4

WORKDIR /app

COPY requirements.txt ./requirements.txt

RUN pip install --upgrade pip
RUN pip install  --no-cache-dir -r requirements.txt

EXPOSE 8501

COPY . /app
COPY .streamlit ./.streamlit 

ENTRYPOINT ["streamlit" ,"run"]

CMD ["app.py"]
